[package]
name = "tscn-parser"
version = "0.5.7"
authors = ["Artjoms Travkovs <atravkovs@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1.3"
indexmap = "1.3"
nalgebra = "0.19"
lazy_static = "1.4"
