[package]
name = "tscn-parser"
version = "0.2.0"
authors = ["Artjoms Travkovs <atravkovs@gmail.com>"]
edition = "2018"

[dependencies]
glob = "0.3"
regex = "1.3"
indexmap = "1.3"
fletcher = "0.0.1"
nalgebra = "0.19"
lazy_static = "1.4"
